config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  root :to => 'homes#top'

  namespace :admin do
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :admin_notices, only: [:index, :new, :create, :destroy] do
      collection do
        get :users
      end
    end
  end

  resources :users, only: [:index, :show]

  resources :products, only: [:index] do
    collection do
      post 'update_all'
    end
  end

  resources :cart_items do
    collection do
      post 'update_all'
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  resources :shares do
    resource :favorites, only: [:create, :destroy]
  end

  resources :user_notices, only: [:index, :new, :create, :destroy]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :admin_notices, dependent: :destroy

  validates :email, :password, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_notice.rb
class AdminNotice < ApplicationRecord
  belongs_to :admin

  validates :information_title, :information_body, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, :product_id, :quantity, presence: true

  validates :quantity, numericality: { only_integer: true }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :title, :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_detalis, dependent: :destroy
end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_detalis, dependent: :destroy

  validates :name, :introduction, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :share_information, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :favorites, dependent: :destroy
  has_many :admin_notices, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :email, :name, :password, :postal_code, :phone_number, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/user_notice.rb
class UserNotice < ApplicationRecord
  belongs_to :user

  validates :information_title, :information_body, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :share_user, only: [:edit, :update, :delete]

  def index
    @shares = Share.order(created_at: :desc).page(params[:page]).per(3)
  end

  def new
    @share = Share.new
  end

  def create
    @share = Share.new(share_params)
    @share.user_id = current_user.id
    if @share.save
      redirect_to shares_path, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @share = Share.find(params[:id])
  end

  def update
    @share = Share.find(params[:id])
    if @share.update(share_params)
      redirect_to shares_path, notice: '変更しました'
    else
      render :edit
    end
  end

  def destroy
    @share = Share.find(params[:id])
    @share.destroy
    redirect_to shares_path
  end

  def share_user
    @share = Share.find(params[:id])
    redirect_to shares_path unless @share.user_id == current_user.id
  end

  private

  def share_params
    params.require(:share).permit(:share_information_title, :share_information)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shares/edit.html.erb
<div class="container">
  <%= form_with model: @share, local:true do |f| %>
  <%= render 'layouts/error', model: f.object %>
    <h3>投稿内容編集</h3>
      <div class="row">
        <div class="form-group ml-3" style="width:50rem;">
           <label for="share_information_title">タイトル</label><br>
           <%= f.text_field :share_information_title,class:'col-10' %><br>
           <label for="share_information">内容</label><br>
           <%= f.text_area :share_information,class:'col-10' %><br>
           <%= f.submit '変更', class:'btn btn-info' %>
        </div>
      </div>
  <% end %>
</div>

app/views/shares/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="ml-5">共有事項</h3>
     <% if @shares.empty?%>
        <h3 style="margin:100px 0 0 280px">共有事項がありません <i class="fas fa-share"></i></h3>
        <div class="ml-auto"><%= link_to"共有事項作成",new_share_path, class:"btn btn-secondary" %></div>
     <% else %>
    <div class="ml-auto"><%= link_to"共有事項作成",new_share_path, class:"btn btn-secondary" %></div>
  </div>
  <div class="row">
    <div class="mx-auto w-auto mt-3">
      <div class="col_md_8">
        <% @shares.each do |share| %>
          <div class="mb-3">
            <div class="card border-dark" style="width: 50rem;">
              <div class="card-header" style="background-color: #FFE4E1;">
                <%= share.share_information_title %>
                <span style="font-size:small;">[<%= share.created_at.strftime("%m月%-d日%k時%-M分")%>]</span>
              </div>
              <div class="card-body">
                <p class="card-text"><%= share.share_information %></p>
                <div id="share_<%= share.id %>">
                <div class="favorite-btn"><%= render 'favorites/favorite', share: share %></div>
                </div>
                <% if share.user == current_user %>
                <%= link_to"編集",edit_share_path(share.id), class:"btn btn-secondary" %>
                <%= link_to"削除",share_path(share.id), method: :delete, data: { confirm: "【確認】削除してもよろしいですか？" },class:"btn btn-secondary" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto"><%= paginate @shares%></div>
  </div>
  <% end %>
</div>

app/views/shares/new.html.erb
<div class="container">
  <%= form_with model: @share, local:true do |f| %>
    <h3>共有事項作成</h3>
    <%= render 'layouts/error', model: f.object %>
      <div class="row">
        <div class="form-group ml-3" style="width:50rem;">
           <label for="share_information_title">タイトル</label><br>
           <%= f.text_field :share_information_title,class:'col-9' %><br>
           <label for="share_information">内容</label><br>
           <%= f.text_area :share_information,class:'col-9' %><br>
           <%= f.submit '投稿', class:'btn btn-info' %>
        </div>
      </div>
  <% end %>
</div>