config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  root :to => 'homes#top'

  namespace :admin do
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :admin_notices, only: [:index, :new, :create, :destroy] do
      collection do
        get :users
      end
    end
  end

  resources :users, only: [:index, :show]

  resources :products, only: [:index] do
    collection do
      post 'update_all'
    end
  end

  resources :cart_items do
    collection do
      post 'update_all'
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  resources :shares do
    resource :favorites, only: [:create, :destroy]
  end

  resources :user_notices, only: [:index, :new, :create, :destroy]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :admin_notices, dependent: :destroy

  validates :email, :password, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_notice.rb
class AdminNotice < ApplicationRecord
  belongs_to :admin

  validates :information_title, :information_body, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, :product_id, :quantity, presence: true

  validates :quantity, numericality: { only_integer: true }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :title, :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_detalis, dependent: :destroy
end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_detalis, dependent: :destroy

  validates :name, :introduction, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :share_information, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :favorites, dependent: :destroy
  has_many :admin_notices, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :email, :name, :password, :postal_code, :phone_number, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/user_notice.rb
class UserNotice < ApplicationRecord
  belongs_to :user

  validates :information_title, :information_body, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path, notice: "作成しました"
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path, notice: '変更しました'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event).permit(:user_id, :title, :body, :start_date, :end_date)
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="container">
  <%= form_with model: @event, local:true do |f| %>
  <%= render 'layouts/error', model: f.object %>
    <h3>予定内容編集</h3>
      <div class="row">
        <div class="form-group ml-3" style="width:50rem;">
           <label for="title">タイトル</label><br>
           <%= f.text_field :title,class:'col-9' %><br>
           <label for="body">内容</label><br>
           <%= f.text_area :body,class:'col-9' %><br>
           <label for="start_date">開始時刻</label><br>
           <%= f.datetime_select :start_date %><br>
           <label for="end_date">終了時刻</label><br>
           <%= f.datetime_select :end_date %><br>
           <%= f.submit '変更', class:'btn btn-info' %>
        </div>
      </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div id="calendar"></div>
  <div class="mt-3" style="text-align: end"><%= link_to "予定作成", new_event_path, class:"btn btn-success" %></div>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= form_with model: @event, local:true do |f| %>
  <%= render 'layouts/error', model: f.object %>
    <h3>予定作成</h3>
    <div class="row">
      <div class="form-group ml-3" style="width:50rem;">
         <label for="title">件名</label><br>
         <%= f.text_field :title,class:'col-9' %><br>
         <label for="body">内容</label><br>
         <%= f.text_area :body,class:'col-9' %><br>
         <label for="start_date">開始時刻</label><br>
         <%= f.datetime_select :start_date %><br>
         <label for="end_date">終了時刻</label><br>
         <%= f.datetime_select :end_date %><br>
         <%= f.submit '送信', class:'btn btn-info' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
   <h3>予定詳細</h3>
   <div class="card border-dark" style="width: 30rem; margin:0 auto;">
        <div class="card-header" style="background-color: #63ceef;"> <%= @event.title %></div>
        <div class="card-body">
          <p class="card-text"><%= @event.body %></p>
          <p class="card-text"><%= @event.start_date.strftime("%m月%d日 %H時%M分") %> ~ <%= @event.end_date.strftime("%m月%d日 %H時%M分") %></p>
          <p style='text-align: end'>
              <%= link_to "戻る", events_path,class: 'btn btn-info' %>
              <% if current_user = @event.user %>
              <%= link_to '編集', edit_event_path(@event), class: 'btn btn-success' %>
              <%= link_to '削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
             <% end %>
          </p>
        </div>
      </div>
</div>