config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  root :to => 'homes#top'

  namespace :admin do
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :admin_notices, only: [:index, :new, :create, :destroy] do
      collection do
        get :users
      end
    end
  end

  resources :users, only: [:index, :show]

  resources :products, only: [:index] do
    collection do
      post 'update_all'
    end
  end

  resources :cart_items do
    collection do
      post 'update_all'
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  resources :shares do
    resource :favorites, only: [:create, :destroy]
  end

  resources :user_notices, only: [:index, :new, :create, :destroy]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :admin_notices, dependent: :destroy

  validates :email, :password, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_notice.rb
class AdminNotice < ApplicationRecord
  belongs_to :admin

  validates :information_title, :information_body, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, :product_id, :quantity, presence: true

  validates :quantity, numericality: { only_integer: true }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :title, :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_detalis, dependent: :destroy
end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_detalis, dependent: :destroy

  validates :name, :introduction, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :share_information, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :favorites, dependent: :destroy
  has_many :admin_notices, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :email, :name, :password, :postal_code, :phone_number, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/user_notice.rb
class UserNotice < ApplicationRecord
  belongs_to :user

  validates :information_title, :information_body, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cart_items = current_user.cart_items
  end

  def create
    @cart_items = current_user.cart_items.all
    cart_item_params.each do |cart_item_param|
      cart_item = @cart_items.find_by(product_id: cart_item_param['product_id']) # カートに入れる商品idとカートに入っている商品id取得
      if cart_item.nil?
        # カゴの中に同じ商品がなかった場合
        current_user.cart_items.create(cart_item_param)
      else
        # カゴの中に同じ商品があった場合
        new_quantity = cart_item.quantity + cart_item_param['quantity'].to_i
        cart_item.update_attribute(:quantity, new_quantity)
      end
    end
    # カートのリフレッシュ
    @cart_items = current_user.cart_items.all
    redirect_to cart_items_path
  end

  def update_all
    cart_item_update_quantity_params.each do |param|
      cart_item = CartItem.find(param['id'])
      cart_item.update(param)
    end
    redirect_to cart_items_path, notice: '数量変更しました'
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path, notice: '削除しました'
  end

  def destroy_all
    @cart_items = current_user.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path, notice: 'カート内商品全て削除しました'
  end

  private

  # viewから送られてきたカートに追加したい商品
  # ただし, quantityが0のものも送られてくるので事前フィルタリングする
  def cart_item_params
    params.require(:cart_item).permit(cart_item: [:product_id, :quantity])["cart_item"].filter do |cart_item_param|
      cart_item_param['quantity'] != '0'
    end
  end

  # カートアイテムの個数変更用
  def cart_item_update_quantity_params
    params.require(:cart_item).permit(cart_item: [:id, :quantity])["cart_item"]
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/index.html.erb
<div class="container mt-3">
  <h3>発注商品一覧</h3>
  <div class="row">
    <% if @cart_items.empty?%>
      <div class="w-auto mx-auto mt-3">
        <h3 class="mt-3 ml-3">カート内に商品がありません <i class="fas fa-cart-arrow-down"></i></h3>
        <div style="text-align: center; margin-top: 50px;"><%= link_to "商品一覧へ", products_path, class: "btn btn-info" %></div>
      </div>
    <% else %>
    <%= form_with model: CartItem, url: update_all_cart_items_url, method: :post, local: true, class: 'table' do |f| %>
        <div class="mb-1" style=" text-align: end">
          <%= link_to "カートを空にする",destroy_all_cart_items_path,method: :delete, class: 'btn btn-danger' %>
        </div>
    <table class="table table-bordered table_border_radius table-light border-dark">
      <thead>
        <tr>
          <th>商品名</th>
          <th>商品概要</th>
          <th>発注数</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
        <tr>
          <td><%= cart_item.product.name %></td>
          <td><%= cart_item.product.introduction %></td>
          <td><%= f.hidden_field 'cart_item[][id]', value: cart_item.id %>
          <%= f.select 'cart_item[][quantity]', [*(0..20)], {selected: cart_item.quantity} %></td>
          <td><%=link_to "削除", cart_item_path(cart_item),method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
          <% end %>
         <tr>
            <td colspan='4' style='text-align: end'><%= f.submit "数量更新", class: "btn btn-outline-primary" %></td>
          </tr>
      </tbody>
    </table>
    <% end %>
    <div class="ml-auto">
     <div class="ml-5"><%= link_to "発注確認画面へ", confirm_orders_path,method: :post, class: 'btn btn-success' %></div>
    </div>
  </div>
  <% end %>
</div>