config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  root :to => 'homes#top'

  namespace :admin do
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :admin_notices, only: [:index, :new, :create, :destroy] do
      collection do
        get :users
      end
    end
  end

  resources :users, only: [:index, :show]

  resources :products, only: [:index] do
    collection do
      post 'update_all'
    end
  end

  resources :cart_items do
    collection do
      post 'update_all'
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  resources :shares do
    resource :favorites, only: [:create, :destroy]
  end

  resources :user_notices, only: [:index, :new, :create, :destroy]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :admin_notices, dependent: :destroy

  validates :email, :password, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_notice.rb
class AdminNotice < ApplicationRecord
  belongs_to :admin

  validates :information_title, :information_body, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, :product_id, :quantity, presence: true

  validates :quantity, numericality: { only_integer: true }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :title, :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_detalis, dependent: :destroy
end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_detalis, dependent: :destroy

  validates :name, :introduction, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :share_information, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :favorites, dependent: :destroy
  has_many :admin_notices, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :email, :name, :password, :postal_code, :phone_number, presence: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/user_notice.rb
class UserNotice < ApplicationRecord
  belongs_to :user

  validates :information_title, :information_body, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: '商品作成しました'
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_products_path, notice: '変更しました'
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :introduction, :quantity, :is_active)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
    @cart_item = CartItem.new
  end

  def update_all
    product_update_quantity_params.each do |param|
      product = Product.find(param['id'])
      product.update(param)
    end
    redirect_to products_path, notice: '在庫数更新しました'
  end

  private

  def product_update_params
    params.require(:product).permit(:name, :introduction, :quantity)
  end

  def product_update_quantity_params
    params.require(:product).permit(product: [:id, :quantity])["product"]
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/index.html.erb
<div class="container mt-3">
  <h3>受注可能商品一覧</h3>
  <div class="row">
      <div class="d-flex ml-auto mb-3">
        <div><%= link_to"商品登録",new_admin_product_path, class:"btn btn-secondary" %></div>
      </div>
    <table class="table table_border_radius border-dark table-bordered table-light">
      <thead>
        <tr>
          <th>商品名</th>
          <th>商品概要</th>
          <th>販売状況</th>
          <th>販売状況編集</th>
          <!--<th></th>-->
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.introduction %></td>
          <td><% if product.is_active == false %>
                  <p class="text-success">受注可</p>
                <% else %>
                  <p class="text-black-50">受注不可</p>
                <% end %>
          </td>
          <td style=":width:20rem;"><%= form_with model: [:admin, product], local:true do |f| %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '受注可', value:false %>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '受注不可', value:true %>
              <%= f.submit '変更を保存', class:'btn btn-outline-success'%>
              <% end %></td>
          <!--<td><%#= link_to"削除",admin_product_path(product.id), method: :delete, class:"btn btn-danger" %></td>-->
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
 <%= form_with model: [:admin, @product], local:true do |f| %>
  <%= render 'layouts/error', model: f.object %>
  <h3>商品登録</h3>
  <div class="row">
    <div class="form-group ml-3" style="width:50rem;">
      <div class="form-group">
         <label for="name">商品名</label><br>
         <%= f.text_field :name,class:'col-7' %><br>
         <label for="introduction">商品概要</label><br>
         <%= f.text_area :introduction,class:'col-7' %><br>
         <%= f.submit '商品登録', class:'btn btn-info' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-6">
      <h3>店舗在庫管理</h3>
      <%= form_with model: Product, url: update_all_products_url, method: :post, local: true, class: 'table' do |f| %>
       <table class="table table-bordered border-dark table_border_radius table-light">
        <thead>
          <tr>
            <th>商品名</th>
            <th>商品概要</th>
            <th>店舗残数</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
           <tr>
            <%= f.hidden_field 'product[][id]', value: product.id %> <!--商品idを配列で渡す-->
            <td><%= product.name %></td>
            <td><%= product.introduction %></td>
            <td><%= f.select 'product[][quantity]', [*(0..100)], {selected: product.quantity} %></td> <!--商品の個数を配列で渡す-->
           </tr>
          <% end %>
           <tr>
            <td colspan='3' style="text-align: end"><%= f.submit "更新", class: "btn btn-outline-primary" %></td>
           </tr>
        </tbody>
       </table>
      <% end %>
    </div>

    <div class="col-6">
     <h3>発注可能商品一覧</h3>
      <%= form_with model: @cart_item, url: cart_items_path(@cart_item), local: true, class: 'table' do |f| %>
        <table class="table table-bordered border-dark table_border_radius table-light">
          <thead>
            <tr>
              <th>商品名</th>
              <th>商品概要</th>
              <th>発注数</th>
              <th>販売状況</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <%= f.hidden_field 'cart_item[][product_id]', value: product.id %> <!--カートアイテムモデルの商品idを配列で渡す-->
                <td><%= product.name %></td>
                <td><%= product.introduction %></td>
                <td><% if product.is_active == false %>
                    <%= f.select 'cart_item[][quantity]', [*(0..20)], {selected: 0} %>
                    <% else %>
                    ×</td> <!--カートアイテムモデルの個数を配列で渡す-->
                    <% end %>
                <td><% if product.is_active == false %>
                      <div class="text-success">注文可能</div>
                    <% else %>
                      <div class="text-black-50">注文不可</div>
                    <% end %>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan='4' style='text-align: end'><%= f.submit "発注", class: "btn btn-outline-success" %></td>
            </tr>
           </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>